### ISSUE TITLE
sleep after go server

### ISSUE THREAD

**Issue by zdyj3170101136** [tigrannajaryan/exp-otelproto#7]
It is very easy exit after make benchmark
`2022/05/10 18:10:35 dial:dial tcp [::]:44698: connect: no route to host`

So i advised sleep one second after go server listen in https://github.com/tigrannajaryan/exp-otelproto/blob/master/core/experiment.go#L61

**Comment by tigrannajaryan** [comment]
Please do not submit issues. This is a personal repository that does not accept external contributions.
